services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-template
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    networks:
      - postgres_network

networks:
  postgres_network:
    external: true
